server:
  port: 8082

spring:
  application:
    name: mybatis-study

  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis-study?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
logging:
  level:
    root: warn
    com.xgit.starter.mapper: trace
  pattern:
    console: '%p%m%n'



